### ISSUE TITLE
Installation routine does not run through

### ISSUE THREAD

**Issue by phiadaarr** [munen/emacs.d#9]
The configuration does not work out of the box because:

- org-tempo is not found
- the file "~/src/200ok/200ok-admin/src/export-org-estimations/ok-export-org-estimations.el" is not found
- the file "private_feeds" is not found

I am not sure how to fix this in a way which makes it both easy to use your configuration out of the box and not to complicate things for you @munen in your personal daily use.

**Comment by phiadaarr** [comment]
Ohh, I see that #6 is related. Can you maybe point to that diff on the README or something?

**Comment by munen** [comment]
Thank you for testing!

> org-tempo is not found

Curious. I did just check and `org-tempo` is actually part of GNU Emacs. I have added that change when upgrading to 27.1 according to the documentation: https://orgmode.org/manual/Structure-Templates.html#FOOT148

I'm assuming that it might not exist in older versions, so I have just added a version check: 8e1b013.

> the file "~/src/200ok/200ok-admin/src/export-org-estimations/ok-export-org-estimations.el" is not found

Yes, of course. That's an oversight on my part. It's a personal project that doesn't make sense to open source, yet. I've added a safeguard for it: 1e68e92.

> the file "private_feeds" is not found

Yes, as you said I wanted to fix this long ago in #6, but forgot. I fixed it now in 6f6e6b8.

If you pull, your installation should run through (at least on these three points^^). Could you run and test, again, please?

**Comment by phiadaarr** [comment]
I still get the `org-tempo` error. I have emacs version 26.3 and have not understood yet what exactly has been changed in orgmode regarding those templates.

**Comment by munen** [comment]
> and have not understood yet what exactly has been changed in orgmode regarding those templates.

The default shortcut for org structure templates has been changed. In older versions, if you wanted to have a 
```
#+BEGIN_SRC
#+END_SRC
``` 

block, you'd go to the beginning of a like and write `<s TAB` and you'd get it.

In newer versions, this has been changed to `C-c C-,` which opens a menu from which you can select which type of structure template you want to expand.

The newer version requires way more typing. It's nice, because it makes it possible to explore what kinds of structure templates are available. But, if you know that, already, and you use structure templates a lot, you might like the other syntax better. I fall in the latter category and have years of muscle memory, too. Happily, Emacs supports both options.

I've made a mistake in my last commit and fixed it here: 0d41d54

Please pull again and let me know if it works for you :pray:

**Comment by phiadaarr** [comment]
Works very well! Thanks. The next thing I am stumbling over are the org files. In particular the `ok-export-org-estimation.el` file. I think it would be great also to provide empty org files such that one can just get started. Otherwise, I get errors like `Heading not found on level 1: Inbox` if I do `C-c c t` on a fresh installation. Sorry to bother you so much but I think it pays off if you provide an environment which just can be used without any further tweaking.

**Comment by munen** [comment]
> In particular the ok-export-org-estimation.el file. I think it would be great also to provide empty org files such that one can just get started.

That has nothing to do with your error(; This file is not loaded, because you don't have it, and hence does not interfere with your config.

Your error shows that you don't have the inbox file declared in the capture templates. The config for that, you can find here: https://github.com/munen/emacs.d/#capture-templates

As you can see there, I define the default inbox for `C-c c t` to be in `~/Dropbox/org/things.org` - and within there, in a header called "Inbox". If you add a file in that path with the necessary Header "Inbox", it'll run.

> Sorry to bother you so much but I think it pays off if you provide an environment which just can be used without any further tweaking.

Not a bother at all. However, providing an environment which runs verbatim for other people is not the point of this repository. Let me quote the very first paragraph: "This repository contains my Emacs configuration. It is written and documented in literate programming style."

I think it's a good starting point for anyone to either selectively copy things from my config or to fork it verbatim and change it up. However, it's my config including all kinds of personal things - like email accounts. I do not see a way to make this generic. If I did, then the config would be missing the setup for all kinds of complex stuff like email. And I want to share that with other people so that they don't have to do the work themselves. However, I cannot set up your email account and I cannot set up your capture templates and paths the way you like them(;

**Comment by phiadaarr** [comment]
Okay that does make sense. Thanks for your support! Your repository provided an extremely good starting point for my own hand-crafted configuration. Before I used spacemacs and now I have actual control over the configuration myself :)

**Comment by munen** [comment]
Happy to hear that the repository was helpful in the way intended, thank you^^

And thank you very much in getting involved and making sure that the installation routine runs through - that's definitively a good qualitative goal for a repository which could be used to bootstrap a new hand-crafted config.

Best of luck and enjoyment by using a hand-rolled config instead of using Spacemacs. Both options have their pros, but having your own config has a high likelyhood to understand Emacs better and make stronger use of it in the longterm.

:pray:
